# Generated by Django 5.0.2 on 2025-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
