# Generated by Django 5.0.2 on 2025-06-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0002_usersession_mac_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload_speed', models.FloatField()),
                ('download_speed', models.FloatField()),
                ('total_uploaded', models.BigIntegerField()),
                ('total_downloaded', models.BigIntegerField()),
                ('ping_latency', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captive_portal.usersession')),
            ],
            options={
                'verbose_name': 'Utilisation de la bande passante',
                'verbose_name_plural': 'Utilisations de la bande passante',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Empreinte d'appareil",
                'verbose_name_plural': "Empreintes d'appareils",
            },
        ),
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('DATA_TRANSFER', 'Transfert de données'), ('BANDWIDTH_LIMIT', 'Limite de bande passante atteinte'), ('SUSPICIOUS_ACTIVITY', 'Activité suspecte'), ('DEVICE_CHANGE', "Changement d'appareil")], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('bandwidth_usage', models.FloatField(default=0.0)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='captive_portal.usersession')),
            ],
            options={
                'verbose_name': 'Activité Réseau',
                'verbose_name_plural': 'Activités Réseau',
                'ordering': ['-timestamp'],
            },
        ),
    ]
